volumes:
  pg_data:
  static:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h $DB_HOST -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    container_name: foodgram-backend
    build: ./backend/
    env_file: .env
  frontend:
    container_name: foodgram-frontend
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
      - ../frontend/:/app/result_build/
  gateway:
    build: ./infra/
    restart: always
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static