MAX_LENGTH_RECIPE_CHAR_FIELD = 256
MAX_LENGTH_USER_CHAR_FIELD = 128
MAX_LENGTH_MEASURE_CHAR_FIELD = 64
MAX_LENGTH_TAG_CHAR_FIELD = 32
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_USERNAME = 150
SHORT_TITLE = 128
MAX_STR = 30

MIN_LENGTH_PASSWORD = 8
MIN_DURATION_VALUE = 1
MIN_AMOUNT_VALUE = 1
MIN_COUNT_ADMIN = 1

DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100

USER_NAME_REGEX = r"^[\w.@+-]+\Z"
NON_VALID_USERNAME = r"me"

FILES = {
    "ingredients": "/data/ingredients.csv",
    "tags": "/data/tags.csv"
}
