MAX_LENGTH_256_CHAR_FIELD = 256
MAX_LENGTH_128_CHAR_FIELD = 128
MAX_LENGTH_64_CHAR_FIELD = 64
MAX_LENGTH_32_CHAR_FIELD = 32
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_USERNAME = 150
SHORT_TITLE = 128

MIN_DURATION_VALUE = 1
MIN_AMOUNT_VALUE = 1

DEFAULT_PAGE_SIZE = 10
MAX_PAGE_SIZE = 100

USER_NAME_REGEX = r'^[\w.@+-]+\Z'
NON_VALID_USERNAME = r'me'

FILES = {
    'ingredients': 'ingredients.csv',
}
