# Generated by Django 3.2.3 on 2024-11-21 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_auto_20241121_1912"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FavoriteRecipe",
            new_name="FavouriteRecipe",
        ),
    ]
