# Generated by Django 3.2.3 on 2024-11-22 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_rename_favoriterecipe_favouriterecipe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favouriterecipe",
            options={
                "default_related_name": "favorite_recipe",
                "verbose_name": "Избранный рецепт",
                "verbose_name_plural": "Избранные рецепты",
            },
        ),
        migrations.RemoveConstraint(
            model_name="favouriterecipe",
            name="unique_favorite",
        ),
        migrations.RemoveConstraint(
            model_name="shoppingbusket",
            name="unique_shopping_cart",
        ),
        migrations.AlterField(
            model_name="favouriterecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_recipe",
                to="recipes.recipe",
                verbose_name="Рецепт",
            ),
        ),
        migrations.AlterField(
            model_name="favouriterecipe",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_recipe",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="shoppingbusket",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopping_bucket",
                to="recipes.recipe",
                verbose_name="Рецепт",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/", verbose_name="Аватар"
            ),
        ),
        migrations.AddConstraint(
            model_name="favouriterecipe",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="recipes_favouriterecipe_user_recipe"
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppingbusket",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="recipes_shoppingbusket_user_recipe"
            ),
        ),
    ]
