# Generated by Django 3.2.3 on 2024-11-20 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20241120_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(blank=True, help_text='Время приготовления', null=True, validators=[django.core.validators.MinValueValidator(1, message='Значение не может быть меньше 1 минуты')]),
        ),
    ]
